version: "3.1"
services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FILE_UID: ${FILE_UID}
        FILE_GID: ${FILE_GID}
    ports:
      - "${WWW_PORT}:80"
    volumes:
      - ./docker/apache2/conf_local:/etc/apache2/sites-available
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./application:/var/www/html/
    links:
      - mongodb
    networks:
      - default
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./docker/mongo:/data/db
      - ./docker/mongo_conf/mongod.conf:/etc/mongod.conf:rw
    networks:
      - default

